name: Reusable Workflow
'on':
  workflow_call:
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "This is running from REUSABLE repo"

  reusable-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "hello world"
